/** Build both installation formats from the same reviewed source. No npm packages. */
import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '..');
const version = '27.0.1';
const matches = ['https://www.ea.com/ea-sports-fc/ultimate-team/web-app/*','https://www.ea.com/*/ea-sports-fc/ultimate-team/web-app/*','https://www.easports.com/*/ea-sports-fc/ultimate-team/web-app/*'];
const header = `// ==UserScript==
// @name         Auto-SBC Local
// @namespace    https://github.com/TitiroMonkey/Auto-SBC
// @version      ${version}
// @description  Local EA FC SBC solver with protected cards, Paletools locks and mandatory squad review.
// @author       TitiroMonkey; Auto-SBC Local contributors
// @license      MIT
${matches.map(match => '// @match        ' + match).join('\n')}
// @grant        none
// @run-at       document-idle
// ==/UserScript==
// Generated by frontend/build.mjs; edit frontend/policy.js, native-entry.js and companion.js.
`;
const policy = await readFile(resolve(here, 'policy.js'), 'utf8');
const native = await readFile(resolve(here, 'native-entry.js'), 'utf8');
const companion = await readFile(resolve(here, 'companion.js'), 'utf8');
const source = `${policy}\n${native}\n${companion}`;
await writeFile(resolve(repo, 'tampermonkey-ai-sbc.user.js'), header + source);
await writeFile(resolve(repo, 'plainJavascript.js'), '// Generated by frontend/build.mjs. MIT; see LICENSE.\n' + source);
const out = resolve(repo, 'dist/chrome-extension');
await mkdir(out, { recursive: true });
await writeFile(resolve(out, 'companion.js'), 'window.__autoSBCExtension = true;\n' + source);
await copyFile(resolve(here, 'extension-bridge.js'), resolve(out, 'bridge.js'));
await copyFile(resolve(here, 'extension-worker.js'), resolve(out, 'worker.js'));
await copyFile(resolve(repo, 'LICENSE'), resolve(out, 'LICENSE'));
await writeFile(resolve(out, 'manifest.json'), JSON.stringify({ manifest_version: 3, name: 'Auto-SBC Local',
  version, description: 'Local SBC solver, protected cards and mandatory preview. No auto submit, purchases or pack actions.',
  host_permissions: ['http://127.0.0.1:8000/*'],
  background: { service_worker: 'worker.js' },
  content_scripts: [
    { matches, js: ['bridge.js'], run_at: 'document_idle', world: 'ISOLATED' },
    { matches, js: ['companion.js'], run_at: 'document_idle', world: 'MAIN' }
  ]
}, null, 2) + '\n');
console.log('Built userscript, plain JavaScript and dist/chrome-extension from frontend sources.');
