/** Build both installation formats from the same reviewed source. No npm packages. */
import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '..');
const version = (await readFile(resolve(repo, 'VERSION'), 'utf8')).trim();
if (!/^(0|[1-9]\d*)(\.(0|[1-9]\d*)){0,3}$/.test(version) ||
    version.split('.').some(part => Number(part) > 65535) || !version.split('.').some(part => Number(part) > 0)) {
  throw new Error('VERSION must contain a valid numeric Chrome extension version.');
}
const matches = ['https://www.ea.com/ea-sports-fc/ultimate-team/web-app/*','https://www.ea.com/*/ea-sports-fc/ultimate-team/web-app/*','https://www.easports.com/*/ea-sports-fc/ultimate-team/web-app/*'];
const header = `// ==UserScript==
// @name         Auto-SBC Studio
// @namespace    https://github.com/TitiroMonkey/Auto-SBC
// @version      ${version}
// @description  Local EA FC solver with protected cards, Paletools locks, previews, finite SBC batches and daily plans.
// @author       TitiroMonkey; Auto-SBC Studio contributors
// @license      MIT
${matches.map(match => '// @match        ' + match).join('\n')}
// @grant        none
// @run-at       document-idle
// ==/UserScript==
// Generated by frontend/build.mjs; edit the frontend source modules.
`;
const policy = await readFile(resolve(here, 'policy.js'), 'utf8');
const native = await readFile(resolve(here, 'native-entry.js'), 'utf8');
const batchPolicy = await readFile(resolve(here, 'batch-policy.js'), 'utf8');
const batchRunner = await readFile(resolve(here, 'batch-runner.js'), 'utf8');
const batchReconcile = await readFile(resolve(here, 'batch-reconcile.js'), 'utf8');
const batchReplan = await readFile(resolve(here, 'batch-replan.js'), 'utf8');
const dailyPlan = await readFile(resolve(here, 'daily-plan.js'), 'utf8');
const readRetry = await readFile(resolve(here, 'read-retry.js'), 'utf8');
const companion = await readFile(resolve(here, 'companion.js'), 'utf8');
const source = `window.__autoSBCVersion = ${JSON.stringify(version)};\n${policy}\n${native}\n${batchPolicy}\n${batchRunner}\n${batchReconcile}\n${batchReplan}\n${dailyPlan}\n${readRetry}\n${companion}`;
await writeFile(resolve(repo, 'tampermonkey-ai-sbc.user.js'), header + source);
await writeFile(resolve(repo, 'plainJavascript.js'), '// Generated by frontend/build.mjs. MIT; see LICENSE.\n' + source);
const out = resolve(repo, 'dist/chrome-extension');
await mkdir(out, { recursive: true });
await writeFile(resolve(out, 'companion.js'), 'window.__autoSBCExtension = true;\n' + source);
await copyFile(resolve(here, 'extension-bridge.js'), resolve(out, 'bridge.js'));
await copyFile(resolve(here, 'extension-worker.js'), resolve(out, 'worker.js'));
await copyFile(resolve(repo, 'LICENSE'), resolve(out, 'LICENSE'));
await writeFile(resolve(out, 'manifest.json'), JSON.stringify({ manifest_version: 3, name: 'Auto-SBC Studio',
  version, description: 'Local SBC solver with protected cards and explicit finite auto-submit queues. No purchases, pack opening or player-pick selection.',
  host_permissions: ['http://127.0.0.1:8000/*'],
  background: { service_worker: 'worker.js' },
  content_scripts: [
    { matches, js: ['bridge.js'], run_at: 'document_idle', world: 'ISOLATED' },
    { matches, js: ['companion.js'], run_at: 'document_idle', world: 'MAIN' }
  ]
}, null, 2) + '\n');
console.log('Built userscript, plain JavaScript and dist/chrome-extension from frontend sources.');
